### ISSUE TITLE
Random Thanks for the FastLED port to python

### ISSUE THREAD

**Issue by davepl** [adafruit/Adafruit_CircuitPython_Bundle#101]
I know Issues aren't the correct place for such feedback, but lacking an alternative at all, thought I'd throw out a big "thanks" to whomever did the FastLED port to python.  I needed just the palette code and that's part of what was done, so it was perfect for my needs!

**Comment by davepl** [comment]
And closing so it doesn't stay open!

**Comment by ladyada** [comment]
hug report for @PaintYourDragon  :)
