### ISSUE TITLE
adafruit_ssd1306 throws ImportError on framebuf import

### ISSUE THREAD

**Issue by hukuzatuna** [adafruit/Adafruit_CircuitPython_Bundle#11]
CircuitPython 2.0, Feather M0 Adalogger, OLED FeatherWing.

code.py output:
Traceback (most recent call last):
  File "code.py", line 26, in <module>
  File "/lib/adafruit_ssd1306/__init__.py", line 1, in <module>
  File "libraries/drivers/ssd1306/adafruit_ssd1306/ssd1306.py", line 3, in <module>
ImportError: no module named 'framebuf'

**Comment by tdicola** [comment]
Check the guide here: https://learn.adafruit.com/micropython-hardware-ssd1306-oled-display/software  You'll want to install the pure python framebuf module it mentions:

"Furthermore, CircuitPython builds after 0.8.1 do not have the framebuf module built in to save flash space. So, please download and install the [pure Python implementation of framebuf](https://github.com/adafruit/micropython-adafruit-framebuf/releases) and copy it to the board as well.
Before continuing make sure your board's root filesystem has the adafruit_ssd1306, adafruit_bus_device, adafruit_register and framebuf folders/modules copied over."
