### ISSUE TITLE
Request a library for MCP23S08, a SPI GPIO expander

### ISSUE THREAD

**Issue by ngmacha** [adafruit/Adafruit_CircuitPython_Bundle#110]
The library bundle includes MCP23008/17, the I2C GPIO expander. Is it possible also to create a library for MCP23S08/S17, the similar SPI GPIO expander?

**Comment by ladyada** [comment]
we don't have any plans for it, we don't even own one of those chips! 

would you be interested? it could be an fairly easy 'rewrite' of the I2C version to use SPI. if so, please open up an issue https://github.com/adafruit/circuitpython and we can help you!
