### ISSUE TITLE
Exact location to copy files of circuitPython Bundle

### ISSUE THREAD

**Issue by sharoseali** [adafruit/Adafruit_CircuitPython_Bundle#113]
> To use the bundle download the zip (not source zip) from the latest release, unzip it and copy over the subfolders, such as lib, into the root of your CircuitPython device. Make sure to indicate that it should be merged with the existing folder when it exists.

@ladyada
Hi! i am working on nvidia jetson TX2  and i want to use circuit python. The information provided to install the circuit python files do not confirms exact location . There are 2 to 3 lib folders, in which lib folder you i copy all these files . please mention it.
**Q2: As i want to use adafruit pca9685 for servo control.  please also explain this line
circuitpython-build-bundles --filename_prefix adafruit-circuitpython-bundle --library_location libraries --library_depth 2** 
As i am using Nvidia jetson TX2 with connecting Adafruit pca9685, will this library help me in controlling my servos on PWM in python?.. kindly answer !!
regards rose

**Comment by ladyada** [comment]
right now we don't have a blinka implementation for the NVidia Jetson TX2 - so this may all be moot. If you're interested in adding one, that would be awesome and very much appreciated, we don't own one of these boards. You'd add your code to the Adafruit Blinka repo. Then on linux you'd use pip to install :)
