### ISSUE TITLE
Documentation: MAX7219 references micropython class; should be the new adafruit one

### ISSUE THREAD

**Issue by mrmcwethy** [adafruit/Adafruit_CircuitPython_Bundle#12]
We need to create a ReadTheDocs file for adafruit max7219 and update circuitpython/index.rst to reference it.  One file we could use is kept in https://github.com/adafruit/Adafruit_CircuitPython_MAX7219/blob/master/README.rst

**Comment by tannewt** [comment]
I've created a new ReadTheDocs for it: http://circuitpython.readthedocs.io/projects/max7219/en/latest/

Would you mind adding the link to the CircuitPython docs?

**Comment by mrmcwethy** [comment]
Sure no problem
Mike 

    On Thursday, September 7, 2017 10:47 AM, Scott Shawcroft <notifications@github.com> wrote:
 

 I've created a new ReadTheDocs for it: http://circuitpython.readthedocs.io/projects/max7219/en/latest/Would you mind adding the link to the CircuitPython docs?—

**Comment by tannewt** [comment]
This was done in https://github.com/adafruit/circuitpython/commit/dd72fe694526d2b468e189b70ae732f7568fe6e4
