### ISSUE TITLE
Empty file

### ISSUE THREAD

**Issue by Tasm-Devil** [adafruit/Adafruit_CircuitPython_Bundle#129]
There is an led_animation_simpletest.py with 0 Bytes in the newest 4.0 release. Where does it come from?

**Comment by kattni** [comment]
It's from here: https://github.com/adafruit/Adafruit_CircuitPython_LED_Animation/blob/master/examples/led_animation_simpletest.py

There was apparently no content added to that example. If you could file an issue on that repo, that would be great. Thanks!

**Comment by Tasm-Devil** [comment]
ok. I watch this repo and maybe I will write some demo-code.
