### ISSUE TITLE
Build a set of bundles with different CircuitPython releases automatically

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_Bundle#13]
Make the main bundle builder be a routine and call it with different CircuitPython version args. `make clean;make` mpy-cross.

**Comment by dhalbert** [comment]
Also add `git submodule update` to `update-submodules.py`. And do that in `circuitpython` as well when switching tags.

**Comment by tannewt** [comment]
Done in e6ae4a596e23a7b67a8f3e2fb6ceeed7748554db
