### ISSUE TITLE
Add MAX7219 library to bundle.

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_Bundle#14]

**Comment by tannewt** [comment]
Its in here: https://github.com/adafruit/Adafruit_CircuitPython_Bundle/tree/master/libraries/drivers

I think we need to add `git submodule update` to the update script.

**Comment by dhalbert** [comment]
Yah, I ran `./update-submodules.sh`.

**Comment by dhalbert** [comment]
There was a `git submodule update` already in `update-submodules.sh`. But there was not a `git submodule init`, which was needed. Adding as part of #13.
