### ISSUE TITLE
fetch: Label is not defined

### ISSUE THREAD

**Issue by kjhulin** [adafruit/Adafruit_CircuitPython_Bundle#150]
Using adafruit-circuitpython-pyportal-en_US-4.0.0-beta.6.uf2 with library bundle adafruit-circuitpython-bundle-4.x-mpy-20190329.zip.

Error when running Adabox sample code:

`
import time
import board
from adafruit_pyportal import PyPortal

\# Set up where we'll be fetching data from 
DATA_SOURCE = "https://www.adafruit.com/api/quotes.php"
QUOTE_LOCATION = [0, 'text']
AUTHOR_LOCATION = [0, 'author']

cwd = ("/"+\_\_file\_\_).rsplit('/', 1)[0]
pyportal = PyPortal(url=DATA_SOURCE,
                    json_path=(QUOTE_LOCATION, AUTHOR_LOCATION),
                    status_neopixel=board.NEOPIXEL,
                    default_bg=cwd+"/quote_background.bmp",
                    text_font=cwd+"/fonts/Arial-ItalicMT-17.bdf",
                    text_position=((20, 40),  # quote location
                                   (100, 190)), # author location
                    text_color=(0xFFFFFF,  # quote text color
                                0x8080FF), # author text color
                    text_wrap=(35, # characters to wrap for quote
                               0), # no wrap for author
                    text_maxlen=(170, 30), # max text size for quote & author
                    debug=True)

\# speed up projects with lots of text by preloading the font! 
pyportal.preload_font()

while True:
    try:
        value = pyportal.fetch()
        print("Response is", value)
    except RuntimeError as e:
        print("Some error occured, retrying! -", e)
    time.sleep(0)
`

Error:
`Traceback (most rececnt call last):  
  File "code.py", line 33, in <module>  
  File "code.py, line 30, in <module>  
  File "adafruit_pyportal.py", line 765, in fetch  
  File "adafruit_pyportal.py", line 480, in set_text  
NameError: name 'Label' is not defined  
`

**Comment by ladyada** [comment]
hiya please go thru this guide
https://learn.adafruit.com/adafruit-pyportal/updating-your-pyportal
