### ISSUE TITLE
Add Adafruit_CircuitPython_DHTlib to bundle.  

### ISSUE THREAD

**Issue by mrmcwethy** [adafruit/Adafruit_CircuitPython_Bundle#16]
@tannewt : First create a placeholder bundle library driver project and import my project into it: https://github.com/mrmcwethy/Adafruit_CircuitPython_DHTlib.git

The i can do the work to add the library to the bundle

**Comment by tannewt** [comment]
Ok, its forked to adafruit now: https://github.com/adafruit/Adafruit_CircuitPython_DHTlib

And docs set up: http://circuitpython.readthedocs.io/projects/dht/en/latest/

Thanks @mrmcwethy !

**Comment by tannewt** [comment]
Fixed in 48f6191f815a6bcb0153cbde4da1a082160e50a5
