### ISSUE TITLE
Discontinue 2.x and 3.x bundle

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_Bundle#187]
We will support only one previous version of the bundle. It is time to discontinue the 2.x bundle, and nearly time to discontinue the 3.x bundle (when 5.0 is released). We will create a section on the CircuitPython FAQ or Troubleshooting page (or both) with a static link to the last build of each, and stop building moving forward. It makes sense to wait until we release 5.0 and discontinue both at the same time.

CircuitPython.org/libraries will need to be updated at that time.

We need to remove the 3.x backwards compatibility from libraries. It is no longer necessary.

**Comment by tannewt** [comment]
This is done. :-)
