### ISSUE TITLE
Update drivers, helpers, examples using wait_for_frame, refresh_soon

### ISSUE THREAD

**Issue by anecdata** [adafruit/Adafruit_CircuitPython_Bundle#195]
For 5.0 displayio compatibility.

grep of Library Bundle shows wait_for_frame or refresh_soon used in:
```
- [x] pyportal (drivers and helpers)
- [x] miniqr/examples/
- [x] turtle (drivers and helpers)
- [x] display-text/examples/ (drivers and helpers)
- [x] pybadger
- [x] pyoa (drivers and helpers)
- [x] slideshow
```
(Learn guides also extensively use the pre-5.x displayio refresh paradigm)

**Comment by jerryneedell** [comment]
slideshow has been updated - new release yesterday...

**Comment by makermelissa** [comment]
It appears the proper replacement for `wait_for_frame()` is `refresh(target_frames_per_second=60)`
To make compatible with both CP 4.1 and CP 5.0, it looks like the following code block works:
```
try:
    display.refresh(target_frames_per_second=60)
except AttributeError:
    display.wait_for_frame()
```

**Comment by makermelissa** [comment]
It should now all be updated. For a lot of the code, a simple grep may still show wait_for_frame() or refresh_soon(), which are in try blocks so that the code also works in 4.0.
