### ISSUE TITLE
`__version__` and `__repo__` are in multiple files in the same library

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_Bundle#199]
I thought we had a policy of putting `__version__` and `__repo__` in `__init__.py` in multi-file libraries, but I appear to be wrong: I see many libraries where those values are in each library file, and sometimes in `__init__.py` and sometimes not.

It seems to me it's redundant for those values to be in each library file, and just takes up space when imported. Am I missing something? I thought this might be due to some cookiecutter template, but I don't see that's true.

**Comment by tannewt** [comment]
I thought they should go into every file because only some files from a library may be copied over.

**Comment by dhalbert** [comment]
Got it.
