### ISSUE TITLE
Drivers to include in new release

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_Bundle#22]
- [x] DS1307: https://github.com/adafruit/Adafruit_CircuitPython_DS1307
- [x] AMG88xx: https://github.com/adafruit/Adafruit_CircuitPython_AMG88xx
- [x] CCS811: https://github.com/adafruit/Adafruit_CircuitPython_CCS811

**Comment by mrmcwethy** [comment]
@kattni I believe this is complete and can be closed.

**Comment by kattni** [comment]
Yes it is! Thank you! Closing.
