### ISSUE TITLE
Add CharLCD Driver

### ISSUE THREAD

**Issue by tannewt** [adafruit/Adafruit_CircuitPython_Bundle#23]
Instructions to add a new driver are here: https://github.com/adafruit/Adafruit_CircuitPython_Bundle#adding-a-library

The driver source is here: https://github.com/adafruit/Adafruit_CircuitPython_CharLCD

**Comment by mrmcwethy** [comment]
I made some minor changes in the code and possible improved the documentation

**Comment by mrmcwethy** [comment]
This is done.  Closing issue.
