### ISSUE TITLE
PulseIO Orange pi PWM issue

### ISSUE THREAD

**Issue by TurryBoeing** [adafruit/Adafruit_CircuitPython_Bundle#266]
Hello,
I am trying circuitpython as explained here: https://learn.adafruit.com/circuitpython-on-orangepi-linux/orange-pi-pc-setup and here: https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/pwm-outputs-servos

When trying the last PWM example, I get the following output:

Traceback (most recent call last):
  File "servo_movement_test.py", line 7, in <module>
    pwm = pulseio.PWMOut(board.D5, duty_cycle=2 ** 15,  frequency=50)
AttributeError: module 'pulseio' has no attribute 'PWMOut'

Any workaround?

**Comment by tannewt** [comment]
Hi, please post to the Adafruit support forums: https://forums.adafruit.com/
