### ISSUE TITLE
Make a bundle for Circuit Python 2.1.0

### ISSUE THREAD

**Issue by dglaude** [adafruit/Adafruit_CircuitPython_Bundle#29]
As described on https://blog.adafruit.com/2017/10/17/circuit-python-2-1-0-released/

**Comment by dhalbert** [comment]
Hi - bundle is being updated and will be out soon. The old bundle works fine -- there should be no inherent incompatibilities. We are adding some newer libraries and bringing the old ones to the latest versions.

**Comment by dhalbert** [comment]
I have updated the release notes to make it clear that the old bundle is OK for 2.1.0. Thanks for bringing it up.
