### ISSUE TITLE
Incorrect PIN assignment for CAN_RX and CAN_TX for Adafruit STM32F405 Feather Express

### ISSUE THREAD

**Issue by Martyx00** [adafruit/Adafruit_CircuitPython_Bundle#303]
Hello,
I was trying to play a bit with the CAN bus and the Adafruit STM32F405 Feather Express in CircuitPython. However, I have encountered a strange thing when setting the TX and RX pins. In the [documentation](https://learn.adafruit.com/adafruit-stm32f405-feather-express/pinouts) and in the [example](https://learn.adafruit.com/assets/98920) the GPIO pin 9 works as CAN_RX and GPIO pin 10 as CAN_TX. However, when I display the values of `board.CAN_RX` and `board.CAN_TX` I get the values inverted.
![CAN](https://user-images.githubusercontent.com/20481897/113127957-9c5b5100-9219-11eb-873b-0016dca1e06b.png)

**Comment by tannewt** [comment]
Please ask questions like these on the support forum: https://forums.adafruit.com/viewforum.php?f=60

Issues on repos are meant for tracking specific code changes.
