### ISSUE TITLE
Adafruit_CircuitPython_74HC165 Driver Library

### ISSUE THREAD

**Issue by woolseyj** [adafruit/Adafruit_CircuitPython_Bundle#319]
I created a new Adafruit_CircuitPython_74HC165 driver library to complement the existing [Adafruit_CircuitPython_74HC595](https://github.com/adafruit/Adafruit_CircuitPython_74HC595) library and would like to release it to Adafruit for incorporation into the main bundle.

Please see previous [issue](https://github.com/adafruit/circuitpython/issues/4777) for additional information and response.

The [Adafruit_CircuitPython_74HC165](https://github.com/woolseyj/Adafruit_CircuitPython_74HC165) library currently exists on my personal GitHub account.  All GitHub Actions are passing.

I see how to incorporate a library into the Community Bundle from the [Creating and sharing a CircuitPython library](https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library) learning guide, but I don't understand how to transfer the library to be hosted under Adafruit's GitHub account and properly added to the bundle.  I could use some assistance.  Your help would be greatly appreciated.

**Comment by ladyada** [comment]
hi if you're writing the driver, it would be best to keep it under your account - we have dozens of community libraries!
