### ISSUE TITLE
Keyboard layouts

### ISSUE THREAD

**Issue by KyootyBella** [adafruit/Adafruit_CircuitPython_Bundle#339]
Is there a way to get more than US keyboard layout? because without that, it can be tricky to run scripts on computers without US keyboard layout on the HID module

**Comment by dhalbert** [comment]
Extra keyboard layouts have been discussed in open and closed issues and PR's in https://github.com/adafruit/Adafruit_CircuitPython_HID. And there is a growing collection of new keyboard layouts in https://github.com/Neradoc/Circuitpython_Keyboard_Layouts, which is under active development (included an automated generator).
