### ISSUE TITLE
adafruit_hid missing from docs index

### ISSUE THREAD

**Issue by rpavlik** [adafruit/Adafruit_CircuitPython_Bundle#342]
Eventually just guessed the url https://circuitpython.readthedocs.io/projects/hid/en/latest/

**Comment by lesamouraipourpre** [comment]
Where were you looking for it?

It's correctly list in https://github.com/adafruit/Adafruit_CircuitPython_Bundle/blob/main/circuitpython_library_list.md until the `Helpers` section.

**Comment by rpavlik** [comment]
I searched for hid on https://circuitpython.readthedocs.io/projects/bundle/en/latest/

**Comment by rpavlik** [comment]
oh, it spells out "human interface device". might be good to put HID in parens since I never thought to search for that.

**Comment by lesamouraipourpre** [comment]
I just realised that you were probably looking at the docs on readthedocs
HID is listed, but it is listed as `USB Human Interface Device (Keyboard and Mouse)` so a quick search for HID wouldn't find it.
