### ISSUE TITLE
Update tags for libraries that contain i2c_device.readinto

### ISSUE THREAD

**Issue by mrmcwethy** [adafruit/Adafruit_CircuitPython_Bundle#35]
Also remove bus_device.I2CDevice.read_into()

Not sure the process. In the Adafruit Bundle project 

1. git submodule foreach "git checkout master"
2. git submodule foreach "git pull"
3. python3 build-bundle.py
4. using the resultant lib/.zip file with .mpy file, for each library of interest, create a small .zip containing the .mpy file or subdirectory
5. create a new release (i.e., new tag) for each library of interest using the above .zip

**Comment by tannewt** [comment]
You should be able to follow this process: https://github.com/adafruit/Adafruit_CircuitPython_Bundle#updating-libraries

Let me know what repos you need release permissions for.

**Comment by mrmcwethy** [comment]
This issue is resolved.
