### ISSUE TITLE
Adafruit_PCA9685 not working

### ISSUE THREAD

**Issue by djairjr** [adafruit/Adafruit_CircuitPython_Bundle#351]
Both versions (6.0 and 7.0) in CircuitPython Bundle.
It appears to be the result of an incomplete build.

Error message informing that there is no PCA9685 attribute in module.
If I try:
`dir (adafruit_pca9685)`

I got:
`['__class__', '__name__', '__file__', '__version__', 'time', '__repo__']`

**Comment by djairjr** [comment]
This version works: https://github.com/adafruit/Adafruit_CircuitPython_PCA9685
The versions contained in both Bundles do not work.

**Comment by dhalbert** [comment]
Closing for now. Let us know if this is still not working for you. Thanks.
