### ISSUE TITLE
Remove superceded lsm303 submodule

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_Bundle#362]

**Comment by tekktrik** [comment]
Is this something worth PRing?  Happy to do so in that case.

**Comment by dhalbert** [comment]
Yes, I added this in a hurry when the original library got split: https://github.com/adafruit/Adafruit_CircuitPython_LSM303

**Comment by tekktrik** [comment]
I'll PR this within the week!
