### ISSUE TITLE
adafruit_imageload is not in the bundle

### ISSUE THREAD

**Issue by romilly** [adafruit/Adafruit_CircuitPython_Bundle#375]
Docs imply that `adafruit_imageload` is in the bundle, and it is needed for some demos, but it is not in the bundle.
Workaround is to copy the package from https://github.com/adafruit/Adafruit_CircuitPython_ImageLoad

**Comment by FoamyGuy** [comment]
I think it is in the bundle. I downloaded the current bundle and I do see it inside of the zip:
![image](https://user-images.githubusercontent.com/2406189/160166330-621f130d-061d-4024-9a19-58a22785b27d.png)

Also it is listed as a submodule directory on this page: https://github.com/adafruit/Adafruit_CircuitPython_Bundle/tree/main/libraries/helpers

What are you seeing that is making it seem like it's missing?

**Comment by romilly** [comment]
Just downloaded the zip, and it's there. I was mistakenly using the version inside the PyPortalUserInterface bundle, which doesn't have it.
