### ISSUE TITLE
Add adafruit_ds3231 to the bundle

### ISSUE THREAD

**Issue by mrmcwethy** [adafruit/Adafruit_CircuitPython_Bundle#4]
Is the DS3221 driver ready for prime time?  The Circuit API document has reference to DS3221 but it is not in the current bundle.  Is there something I can do to get adafruit_ds3231 into the current bundle?

**Comment by tannewt** [comment]
Yeah, I think so. Its just an oversight. Instructions for adding it are here: https://github.com/adafruit/Adafruit_CircuitPython_Bundle#adding-a-library

I'll get to it eventually too. Thanks for pointing it out!

**Comment by dhalbert** [comment]
Closed via https://github.com/adafruit/Adafruit_CircuitPython_Bundle/pull/7. Thanks @mrmcwethy!
