### ISSUE TITLE
link to vl53l0x has a typo in it

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_CircuitPython_Bundle#41]
Pardon the nit-picking. The link to the vl53l0x repo is spell vl530l0x  - I think this is just a typo, but it is confusing.

**Comment by jerryneedell** [comment]
https://github.com/adafruit/Adafruit_CircuitPython_Bundle/tree/master/libraries/drivers

**Comment by dhalbert** [comment]
Fixed. Easy: `git mv` takes care of everything: https://stackoverflow.com/a/18712756/142996
