### ISSUE TITLE
FR: Add type hints to circuit python libraries

### ISSUE THREAD

**Issue by miguelandres** [adafruit/Adafruit_CircuitPython_Bundle#410]
Type hints have been supported since 3.5, and they're massively helpful for static analysis.

I'm sure this is not the right place to put this feature request but I'm not sure where this should go, feel free to point me in the right direction

**Comment by tekktrik** [comment]
Hi!  We actually have issues out for all of the libraries to add type annotations already!  If you want to help out, you can find one of the existing issues in one of the submodule libraires!
