### ISSUE TITLE
Include import names in the library list

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_Bundle#418]
Currently, the library names in https://github.com/adafruit/Adafruit_CircuitPython_Bundle/blob/main/docs/drivers.rst are all descriptive names and do not include the actual library names that one would use in an `import`: `adafruit_whatever`, `neopixel`, `asyncio`, etc. This was already noted in #342 when the `adafruit_hid` library could not be found by searching for "HID".

As part of #344, or just manually, it would be nice to include these import names in the list, so that it would be easy to search for them.

**Comment by jposada202020** [comment]
Maybe we could do this in the following steps:
1. Modify the contents of drivers.rst with the correct import name, and maybe a description as was done for the community libraries as per https://github.com/adafruit/CircuitPython_Community_Bundle/pull/132.
2. Once drivers.rst is updated we change the name to libraries.rst as per #419 
Let me know thanks :)

**Comment by FoamyGuy** [comment]
This is resolved now by #485
