### ISSUE TITLE
AttributeError: module 'pulseio' has no attribute 'PulseOut'

### ISSUE THREAD

**Issue by stephenhudson** [adafruit/Adafruit_CircuitPython_Bundle#425]
Running the lastest version of this with Blinka on a Raspberry Pi 4, I get the error "AttributeError: module 'pulseio' has no attribute 'PulseOut'" PWMout does the same. I have uninstalled and reinstalled and it seems the Pulseio Module is not giving me output capabilities.

**Comment by tekktrik** [comment]
Closing because this is an issue/limitation with Blinka and not the bundle/libraries.
