### ISSUE TITLE
Add Driver for the Adafruit TSL2591 High Dynamic Range Digital Light Sensor

### ISSUE THREAD

**Issue by Apotessar** [adafruit/Adafruit_CircuitPython_Bundle#45]
Hi

It would be cool if the Bundle would support the Adafruit TSL2591 High Dynamic Range Digital Light Sensor right out of the box. Seems legit to me since this is the most capable light sensor in the Adafruit portfolio, and the only one with is able to handle the range needed for modern photography (as support).
Actually I will work on my own driver, witch i'am willing to share when it is done, but first I need to learn more about i2c communication and python in genrell.

Thanks and keep up the good work (finaly I don't have to deal with C anymore ;-) )
Regards
Pascal

**Comment by ladyada** [comment]
hiya the best place to post driver requests is https://github.com/adafruit/circuitpython/issues
thanks :)
