### ISSUE TITLE
Adafruit_CircuitPython_Bundle-main

### ISSUE THREAD

**Issue by Dan-Essin** [adafruit/Adafruit_CircuitPython_Bundle#456]
I just downloaded the latest Adafruit_CircuitPython_Bundle-main.zip.
The readme says to copy the libraries to the device (pico w).
This might be of some use except that
--- the libraries folder and all of it's subfolers in the zip file are EMPTY ---

Please guide me to fixing this

Thank you

**Comment by dhalbert** [comment]
It sounds like you downloaded the **source code** for this repo. You need to download the actual built bundles.

See https://circuitpython.org/libraries or https://github.com/adafruit/Adafruit_CircuitPython_Bundle/releases for the actual bundles.
