### ISSUE TITLE
Remove update scripts from bundle

### ISSUE THREAD

**Issue by ctgreybeard** [adafruit/Adafruit_CircuitPython_Bundle#53]
The XML downloaded by curl -s "https://api.github.com/repos/adafruit/Adafruit_CircuitPython_Bundle/releases/latest" contains no tag "browser_download_url" which leads to a null $download_link.

**Comment by tannewt** [comment]
Hi @ctgreybeard thanks for the report! I need to remove this script. It doesn't support the multiple bundles we have available now. We hope to have auto-updating available in the future but for now please do it manually. Sorry for the inconvenience.

**Comment by tannewt** [comment]
These have been removed.
