### ISSUE TITLE
FancyLED didn't make it into the bundle

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_CircuitPython_Bundle#55]
something went amiss, its not actually in the release file - something to do with subfolder perhaps?

please advise :)

**Comment by tannewt** [comment]
It got dropped because the folder didn't have an `__init__.py` file. This was a hold over from my experience with python 2. The new build tools do support it. The individual zips now have it and I'll do another bundle release to pick it up shortly.

**Comment by tannewt** [comment]
#57 is also the reason Travis passed for the PR but failed overnight.

**Comment by tannewt** [comment]
Re-building the artifacts now for the 20180201-1 release.
