### ISSUE TITLE
Nokia 5110/3310 Library 

### ISSUE THREAD

**Issue by brentru** [adafruit/Adafruit_CircuitPython_Bundle#65]
Working on adding support for the Nokia 5110/3310 monochrome LCD

Product: https://www.adafruit.com/product/338
RasPi/Python Library: https://github.com/adafruit/Adafruit_Nokia_LCD

**Comment by tannewt** [comment]
Did you mean to close this @brentru ?

**Comment by ladyada** [comment]
yah i think he meant to open it in the 'main' repo, its now there https://github.com/adafruit/circuitpython/issues/630
