### ISSUE TITLE
Bundle points to non-existent commit

### ISSUE THREAD

**Issue by cefn** [adafruit/Adafruit_CircuitPython_Bundle#78]
I don't know if this arises from a bot autoupdating, but currently my bundle reports the following...

cefn-bionic-thinkpad:Adafruit_CircuitPython_Bundle$ git submodule update
error: Server does not allow request for unadvertised object 4413dadc54ab08c6085dc3aa536d19f129aa3571
Fetched in submodule path 'libraries/drivers/ds18x20', but it did not contain 4413dadc54ab08c6085dc3aa536d19f129aa3571. Direct fetching of that commit failed.

I suppose ds18x20 may have had that commit but it was removed, but the bundle is still referencing it.

**Comment by dhalbert** [comment]
That commit does indeed exist as the head of master on the ds18x20 right now. I recloned Bundle and did a `git submodule update` and did not get any errors. Could you try again? Either that was a GitHub glitch or your repo clone may have some issue.

**Comment by kattni** [comment]
Closing this. Reopen if issue persists.
